### ISSUE TITLE
未知环境下，获取ContentLength报空指针异常

### ISSUE THREAD

**Issue by hewjinxu** [jdcloud-api/jdcloud-sdk-java#32]
--------- beginning of crash
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: FATAL EXCEPTION: Thread-8
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: Process: com.****.****, PID: 26042
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.InputStream.markSupported()' on a null object reference
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.blackshark.sharktime.model.jdcloud.JdAWSS3V4SignerWithMp4Header.getContentLength(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.blackshark.sharktime.model.jdcloud.JdAWSS3V4SignerWithMp4Header.calculateContentHash(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.amazonaws.auth.AWS4Signer.sign(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.amazonaws.http.AmazonHttpClient.executeHelper(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.amazonaws.http.AmazonHttpClient.execute(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.amazonaws.services.s3.AmazonS3Client.invoke(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.amazonaws.services.s3.AmazonS3Client.abortMultipartUpload(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord$1.run(Unknown Source)
10-27 09:30:50.827 10022 26042 15316 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-27 09:30:50.824  root   945  1062 I chatty  : uid=0(root) /system/vendor/bin/thermal-engine identical 7 lines

**Comment by wdwqw** [comment]
看您的调用栈里好像用的不是这个包中的代码？

**Comment by hewjinxu** [comment]
是基于JdAWSS3V4Signer添加了mpeg4头的自定义类，加了一句addHEAD。
